import { sql } from 'drizzle-orm';
import type { AnyPgColumn } from 'drizzle-orm/pg-core';
import { timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * UUIDv7 primary key, generated by Postgres (ADR-010).
 * Native in PG18 — no extension, no PL/pgSQL shim.
 */
export const primaryKey = () =>
  uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`);

/**
 * Always timestamptz, never plain `timestamp`. A bare `timestamp` silently
 * drops the offset, so a row written in UTC and read in Vancouver is wrong by
 * eight hours with nothing to indicate it.
 *
 * updated_at is maintained by a database trigger, not by the application —
 * `set_updated_at()` is defined in the hand-written section of 0001.
 *
 * **A new table using this needs its own CREATE TRIGGER in the migration that
 * creates it.** drizzle-kit does not model triggers, so nothing generates it
 * and nothing warns you: updated_at simply freezes at insert and every row
 * looks fine. Eight tables missed it between 0002 and 0008 before anyone
 * checked — see 0010 for the repair.
 */
export const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
};

/**
 * The ISO 4217 shape for a check constraint: the database half of
 * IsCurrencyCode (common/dto/currency.ts), which must say the same thing.
 *
 * The bare condition, so a nullable column composes it:
 * sql`${t.currency} is null or ${isCurrencyCode(t.currency)}`. It renders
 * the same SQL the checks always had, so it changes no migration.
 */
export const isCurrencyCode = (column: AnyPgColumn) =>
  sql`${column} ~ '^[A-Z]{3}$'`;

/**
 * The two rules of a language pair (ADR-054), as bare conditions for check
 * constraints, like isCurrencyCode. A document prints in one language or
 * two: no second without a first, and never the same one twice.
 *
 * Neither names a language. Which tags exist is SUPPORTED_LOCALES, checked
 * by the DTOs, so adding a language is a catalogue and a constant, never a
 * migration.
 */
export const secondLanguageNeedsFirst = (
  first: AnyPgColumn,
  second: AnyPgColumn,
) => sql`${second} is null or ${first} is not null`;

export const languagesDiffer = (first: AnyPgColumn, second: AnyPgColumn) =>
  sql`${second} is null or ${second} <> ${first}`;
